server:
  port: 3000

psql:
  host: "localhost"
  port: 5432
  user: "postgres"
  password: "Yersaiyn_2005"
  dbname: "aitu_news"

session:
  session_key: "XGVTzUEaA8t9bCiGc7HXYXXDb2Ad7NTN"
  sessionName: "GSESSIONID"
  sessionKey: "loggedUserID"
  redis:
    connection_timeout_seconds: 10
    network_type: "tcp"
    host: "localhost"
    port: 6379
    password: ""